# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Astro' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'AFNetworking', '~> 3.0'
  pod "MagicalRecord"
  
  # Pods for Astro

  target 'AstroTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AstroUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
